<a href="https://colab.research.google.com/github/shashank89-it/colab/blob/main/Pandas4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Agenda

  - **Restructuring data**
    - pd.melt()
    - pd.pivot()
    - pd.pivot_table()
    - pd.cut()
  - **Dealing with Missing Values**
    - None and nan values
    - isna() and isnull()
    - dropna()
    - fillna()
     
  - **String method in pandas**
    
  - **Handling datetime**


  - **Writing to a file**

In [ ]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 88.7MB/s]

In [ ]:
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 69.5MB/s]

In [ ]:
import pandas as pd
import numpy as np
movies = pd.read_csv('movies.csv', index_col=0)
directors = pd.read_csv('directors.csv',index_col=0)
data = movies.merge(directors, how='left', left_on='director_id',right_on='id')
data.drop(['director_id','id_y'],axis=1,inplace=True)

In [ ]:
data["revenue"]=(data["revenue"]/1000000).round(2)
data["budget"]=(data["budget"]/1000000).round(2)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0.00,7,0.00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0.00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
#Aggregation on groupby

In [ ]:
data.groupby(["director_name","title"])

In [ ]:
data_multi = data.groupby("director_name")[["year","title"]].agg({"year":["min","max"],"title":["count"]})
data_multi

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5
...                           ...   ...   ...
Wes Craven                   1984  2011    10
Wolfgang Petersen            1981  2006     7
Woody Allen                  1977  2013    18
Zack Snyder                  2004  2016     7
Zhang Yimou                  2002  2014     6

[199 rows x 3 columns]

In [ ]:
data_multi.columns

MultiIndex([( 'year',   'min'),
            ( 'year',   'max'),
            ('title', 'count')],
           )

In [ ]:
data_multi.columns = ["_".join(col) for col in data_multi.columns ]

In [ ]:
data_multi.columns

Index(['year_min', 'year_max', 'title_count'], dtype='object')

In [ ]:
data_multi

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

In [ ]:
data_multi.reset_index()

                   director_name  year_min  year_max  title_count
0                     Adam McKay      2004      2015            6
1                  Adam Shankman      2001      2012            8
2    Alejandro González Iñárritu      2000      2015            6
3                    Alex Proyas      1994      2016            5
4                Alexander Payne      1999      2013            5
..                           ...       ...       ...          ...
194                   Wes Craven      1984      2011           10
195            Wolfgang Petersen      1981      2006            7
196                  Woody Allen      1977      2013           18
197                  Zack Snyder      2004      2016            7
198                  Zhang Yimou      2002      2014            6

[199 rows x 4 columns]

In [ ]:
data_multi.columns

Index(['year_min', 'year_max', 'title_count'], dtype='object')

In [ ]:
#Alternate way

In [ ]:
data_multi1 = data.groupby("director_name")[["year","title"]].agg(year_min=("year","min"),
                                                   year_max=("year","max"),
                                                   title_count=("title","count"))

In [ ]:
data_multi1

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

In [ ]:
data_multi1.columns

Index(['year_min', 'year_max', 'title_count'], dtype='object')

In [ ]:
data_multi1.reset_index(inplace=True)

In [ ]:
data_multi1

                   director_name  year_min  year_max  title_count
0                     Adam McKay      2004      2015            6
1                  Adam Shankman      2001      2012            8
2    Alejandro González Iñárritu      2000      2015            6
3                    Alex Proyas      1994      2016            5
4                Alexander Payne      1999      2013            5
..                           ...       ...       ...          ...
194                   Wes Craven      1984      2011           10
195            Wolfgang Petersen      1981      2006            7
196                  Woody Allen      1977      2013           18
197                  Zack Snyder      2004      2016            7
198                  Zhang Yimou      2002      2014            6

[199 rows x 4 columns]

In [ ]:
#most productive director = total #number of movies / (years active = how long is he directing movies)

In [ ]:
data_multi1

                   director_name  year_min  year_max  title_count
0                     Adam McKay      2004      2015            6
1                  Adam Shankman      2001      2012            8
2    Alejandro González Iñárritu      2000      2015            6
3                    Alex Proyas      1994      2016            5
4                Alexander Payne      1999      2013            5
..                           ...       ...       ...          ...
194                   Wes Craven      1984      2011           10
195            Wolfgang Petersen      1981      2006            7
196                  Woody Allen      1977      2013           18
197                  Zack Snyder      2004      2016            7
198                  Zhang Yimou      2002      2014            6

[199 rows x 4 columns]

In [ ]:
data_multi1["years_active"]=data_multi1["year_max"]-data_multi1["year_min"]
data_multi1

,director_name,year_min,year_max,title_count,years_active
0,Adam McKay,2004,2015,6,11
1,Adam Shankman,2001,2012,8,11
2,Alejandro González Iñárritu,2000,2015,6,15
3,Alex Proyas,1994,2016,5,22
4,Alexander Payne,1999,2013,5,14
...,...,...,...,...,...
194,Wes Craven,1984,2011,10,27
195,Wolfgang Petersen,1981,2006,7,25
196,Woody Allen,1977,2013,18,36
197,Zack Snyder,2004,2016,7,12
198,Zhang Yimou,2002,2014,6,12

In [ ]:
data_multi1["movies_per_year"]=data_multi1["title_count"]/data_multi1["years_active"]
data_multi1

,director_name,year_min,year_max,title_count,years_active,movies_per_year
0,Adam McKay,2004,2015,6,11,0.545455
1,Adam Shankman,2001,2012,8,11,0.727273
2,Alejandro González Iñárritu,2000,2015,6,15,0.400000
3,Alex Proyas,1994,2016,5,22,0.227273
4,Alexander Payne,1999,2013,5,14,0.357143
...,...,...,...,...,...,...
194,Wes Craven,1984,2011,10,27,0.370370
195,Wolfgang Petersen,1981,2006,7,25,0.280000
196,Woody Allen,1977,2013,18,36,0.500000
197,Zack Snyder,2004,2016,7,12,0.583333
198,Zhang Yimou,2002,2014,6,12,0.500000

In [ ]:
data_multi1.sort_values(by="movies_per_year",ascending=False)

,director_name,year_min,year_max,title_count,years_active,movies_per_year
190,Tyler Perry,2006,2013,9,7,1.285714
73,Jason Friedberg,2006,2010,5,4,1.250000
169,Shawn Levy,2002,2014,11,12,0.916667
158,Robert Rodriguez,1992,2014,16,22,0.727273
1,Adam Shankman,2001,2012,8,11,0.727273
...,...,...,...,...,...,...
104,Lawrence Kasdan,1985,2012,5,27,0.185185
109,Luc Besson,1985,2014,5,29,0.172414
157,Robert Redford,1980,2010,5,30,0.166667
170,Sidney Lumet,1976,2006,5,30,0.166667
117,Michael Apted,1980,2010,5,30,0.166667

In [ ]:
#Restructuring data

In [ ]:
!gdown 173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ

Downloading...
From: https://drive.google.com/uc?id=173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ
To: /content/Pfizer_1.csv
100% 1.51k/1.51k [00:00<00:00, 7.71MB/s]

In [ ]:
df=pd.read_csv("Pfizer_1.csv")
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       18 non-null     object
 1   Drug_Name  18 non-null     object
 2   Parameter  18 non-null     object
 3   1:30:00    16 non-null     float64
 4   2:30:00    16 non-null     float64
 5   3:30:00    12 non-null     float64
 6   4:30:00    14 non-null     float64
 7   5:30:00    16 non-null     float64
 8   6:30:00    18 non-null     int64
 9   7:30:00    16 non-null     float64
 10  8:30:00    14 non-null     float64
 11  9:30:00    16 non-null     float64
 12  10:30:00   18 non-null     int64
 13  11:30:00   16 non-null     float64
 14  12:30:00   18 non-null     int64
dtypes: float64(9), int64(3), object(3)
memory usage: 2.2+ KB

In [ ]:
df.shape

(18, 15)

In [ ]:
#melting

In [ ]:
pd.melt(df,id_vars=["Date","Drug_Name","Parameter"])

           Date                Drug_Name    Parameter  variable  value
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00   23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00   12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00    NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00    NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00   24.0
..          ...                      ...          ...       ...    ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00   14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00   23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00   28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00   24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00   15.0

[216 rows x 5 columns]

In [ ]:
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
pd.melt(df,id_vars=["Date","Drug_Name","Parameter"],
       var_name="Time",
       value_name="Result").head(60)

          Date                Drug_Name    Parameter     Time  Result
0   15-10-2020  diltiazem hydrochloride  Temperature  1:30:00    23.0
1   15-10-2020  diltiazem hydrochloride     Pressure  1:30:00    12.0
2   15-10-2020      docetaxel injection  Temperature  1:30:00     NaN
3   15-10-2020      docetaxel injection     Pressure  1:30:00     NaN
4   15-10-2020   ketamine hydrochloride  Temperature  1:30:00    24.0
5   15-10-2020   ketamine hydrochloride     Pressure  1:30:00     8.0
6   16-10-2020  diltiazem hydrochloride  Temperature  1:30:00    34.0
7   16-10-2020  diltiazem hydrochloride     Pressure  1:30:00    18.0
8   16-10-2020      docetaxel injection  Temperature  1:30:00    46.0
9   16-10-2020      docetaxel injection     Pressure  1:30:00    23.0
10  16-10-2020   ketamine hydrochloride  Temperature  1:30:00     8.0
11  16-10-2020   ketamine hydrochloride     Pressure  1:30:00    12.0
12  17-10-2020  diltiazem hydrochloride  Temperature  1:30:00    20.0
13  17-10-2020  diltiazem hydrochloride     Pressure  1:30:00     3.0
14  17-10-2020      docetaxel injection  Temperature  1:30:00    12.0
15  17-10-2020      docetaxel injection     Pressure  1:30:00    20.0
16  17-10-2020   ketamine hydrochloride  Temperature  1:30:00    13.0
17  17-10-2020   ketamine hydrochloride     Pressure  1:30:00     8.0
18  15-10-2020  diltiazem hydrochloride  Temperature  2:30:00    22.0
19  15-10-2020  diltiazem hydrochloride     Pressure  2:30:00    13.0
20  15-10-2020      docetaxel injection  Temperature  2:30:00    17.0
21  15-10-2020      docetaxel injection     Pressure  2:30:00    22.0
22  15-10-2020   ketamine hydrochloride  Temperature  2:30:00     NaN
23  15-10-2020   ketamine hydrochloride     Pressure  2:30:00     NaN
24  16-10-2020  diltiazem hydrochloride  Temperature  2:30:00    35.0
25  16-10-2020  diltiazem hydrochloride     Pressure  2:30:00    19.0
26  16-10-2020      docetaxel injection  Temperature  2:30:00    47.0
27  16-10-2020      docetaxel injection     Pressure  2:30:00    24.0
28  16-10-2020   ketamine hydrochloride  Temperature  2:30:00     9.0
29  16-10-2020   ketamine hydrochloride     Pressure  2:30:00    12.0
30  17-10-2020  diltiazem hydrochloride  Temperature  2:30:00    19.0
31  17-10-2020  diltiazem hydrochloride     Pressure  2:30:00     4.0
32  17-10-2020      docetaxel injection  Temperature  2:30:00    13.0
33  17-10-2020      docetaxel injection     Pressure  2:30:00    22.0
34  17-10-2020   ketamine hydrochloride  Temperature  2:30:00    14.0
35  17-10-2020   ketamine hydrochloride     Pressure  2:30:00     9.0
36  15-10-2020  diltiazem hydrochloride  Temperature  3:30:00     NaN
37  15-10-2020  diltiazem hydrochloride     Pressure  3:30:00     NaN
38  15-10-2020      docetaxel injection  Temperature  3:30:00    18.0
39  15-10-2020      docetaxel injection     Pressure  3:30:00    22.0
40  15-10-2020   ketamine hydrochloride  Temperature  3:30:00     NaN
41  15-10-2020   ketamine hydrochloride     Pressure  3:30:00     NaN
42  16-10-2020  diltiazem hydrochloride  Temperature  3:30:00    36.0
43  16-10-2020  diltiazem hydrochloride     Pressure  3:30:00    20.0
44  16-10-2020      docetaxel injection  Temperature  3:30:00     NaN
45  16-10-2020      docetaxel injection     Pressure  3:30:00     NaN
46  16-10-2020   ketamine hydrochloride  Temperature  3:30:00    10.0
47  16-10-2020   ketamine hydrochloride     Pressure  3:30:00    13.0
48  17-10-2020  diltiazem hydrochloride  Temperature  3:30:00    19.0
49  17-10-2020  diltiazem hydrochloride     Pressure  3:30:00     4.0
50  17-10-2020      docetaxel injection  Temperature  3:30:00    14.0
51  17-10-2020      docetaxel injection     Pressure  3:30:00    22.0
52  17-10-2020   ketamine hydrochloride  Temperature  3:30:00    15.0
53  17-10-2020   ketamine hydrochloride     Pressure  3:30:00    10.0
54  15-10-2020  diltiazem hydrochloride  Temperature  4:30:00    21.0
55  15-10-2020  diltiazem hydrochloride     Pressure  4:30:00    11.0
56  15-10-2020      docetaxel injection  Temperature  4:30:00     NaN
57  15-10-2020      docetaxel injection     Pressure  4:30:00     NaN
58  15-10-2020   ketamine hydrochloride  Temperature  4:30:00    27.0
59  15-10-2020   ketamine hydrochloride     Pressure  4:30:00     7.0

In [ ]:
pd.melt(df,id_vars=["Date","Drug_Name"]).head(60)

          Date                Drug_Name   variable        value
0   15-10-2020  diltiazem hydrochloride  Parameter  Temperature
1   15-10-2020  diltiazem hydrochloride  Parameter     Pressure
2   15-10-2020      docetaxel injection  Parameter  Temperature
3   15-10-2020      docetaxel injection  Parameter     Pressure
4   15-10-2020   ketamine hydrochloride  Parameter  Temperature
5   15-10-2020   ketamine hydrochloride  Parameter     Pressure
6   16-10-2020  diltiazem hydrochloride  Parameter  Temperature
7   16-10-2020  diltiazem hydrochloride  Parameter     Pressure
8   16-10-2020      docetaxel injection  Parameter  Temperature
9   16-10-2020      docetaxel injection  Parameter     Pressure
10  16-10-2020   ketamine hydrochloride  Parameter  Temperature
11  16-10-2020   ketamine hydrochloride  Parameter     Pressure
12  17-10-2020  diltiazem hydrochloride  Parameter  Temperature
13  17-10-2020  diltiazem hydrochloride  Parameter     Pressure
14  17-10-2020      docetaxel injection  Parameter  Temperature
15  17-10-2020      docetaxel injection  Parameter     Pressure
16  17-10-2020   ketamine hydrochloride  Parameter  Temperature
17  17-10-2020   ketamine hydrochloride  Parameter     Pressure
18  15-10-2020  diltiazem hydrochloride    1:30:00         23.0
19  15-10-2020  diltiazem hydrochloride    1:30:00         12.0
20  15-10-2020      docetaxel injection    1:30:00          NaN
21  15-10-2020      docetaxel injection    1:30:00          NaN
22  15-10-2020   ketamine hydrochloride    1:30:00         24.0
23  15-10-2020   ketamine hydrochloride    1:30:00          8.0
24  16-10-2020  diltiazem hydrochloride    1:30:00         34.0
25  16-10-2020  diltiazem hydrochloride    1:30:00         18.0
26  16-10-2020      docetaxel injection    1:30:00         46.0
27  16-10-2020      docetaxel injection    1:30:00         23.0
28  16-10-2020   ketamine hydrochloride    1:30:00          8.0
29  16-10-2020   ketamine hydrochloride    1:30:00         12.0
30  17-10-2020  diltiazem hydrochloride    1:30:00         20.0
31  17-10-2020  diltiazem hydrochloride    1:30:00          3.0
32  17-10-2020      docetaxel injection    1:30:00         12.0
33  17-10-2020      docetaxel injection    1:30:00         20.0
34  17-10-2020   ketamine hydrochloride    1:30:00         13.0
35  17-10-2020   ketamine hydrochloride    1:30:00          8.0
36  15-10-2020  diltiazem hydrochloride    2:30:00         22.0
37  15-10-2020  diltiazem hydrochloride    2:30:00         13.0
38  15-10-2020      docetaxel injection    2:30:00         17.0
39  15-10-2020      docetaxel injection    2:30:00         22.0
40  15-10-2020   ketamine hydrochloride    2:30:00          NaN
41  15-10-2020   ketamine hydrochloride    2:30:00          NaN
42  16-10-2020  diltiazem hydrochloride    2:30:00         35.0
43  16-10-2020  diltiazem hydrochloride    2:30:00         19.0
44  16-10-2020      docetaxel injection    2:30:00         47.0
45  16-10-2020      docetaxel injection    2:30:00         24.0
46  16-10-2020   ketamine hydrochloride    2:30:00          9.0
47  16-10-2020   ketamine hydrochloride    2:30:00         12.0
48  17-10-2020  diltiazem hydrochloride    2:30:00         19.0
49  17-10-2020  diltiazem hydrochloride    2:30:00          4.0
50  17-10-2020      docetaxel injection    2:30:00         13.0
51  17-10-2020      docetaxel injection    2:30:00         22.0
52  17-10-2020   ketamine hydrochloride    2:30:00         14.0
53  17-10-2020   ketamine hydrochloride    2:30:00          9.0
54  15-10-2020  diltiazem hydrochloride    3:30:00          NaN
55  15-10-2020  diltiazem hydrochloride    3:30:00          NaN
56  15-10-2020      docetaxel injection    3:30:00         18.0
57  15-10-2020      docetaxel injection    3:30:00         22.0
58  15-10-2020   ketamine hydrochloride    3:30:00          NaN
59  15-10-2020   ketamine hydrochloride    3:30:00          NaN

In [ ]:
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df_melt=pd.melt(df,id_vars=["Date","Drug_Name","Parameter"],
       var_name="Time",
       value_name="Result")
df_melt

           Date                Drug_Name    Parameter      Time  Result
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00    23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00    12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00     NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00     NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00    24.0
..          ...                      ...          ...       ...     ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00    14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00    23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00    28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00    24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00    15.0

[216 rows x 5 columns]

In [ ]:
df_pivot = pd.pivot(df_melt,
         index=["Date","Drug_Name","Parameter"],
         columns="Time",
         values="Result")
df_pivot

Time                                            10:30:00  11:30:00  12:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure         18.0      19.0      20.0
                                   Temperature      20.0      20.0      21.0
           docetaxel injection     Pressure         26.0      29.0      28.0
                                   Temperature      23.0      25.0      25.0
           ketamine hydrochloride  Pressure          9.0       9.0      11.0
                                   Temperature      22.0      21.0      20.0
16-10-2020 diltiazem hydrochloride Pressure         24.0       NaN      27.0
                                   Temperature      40.0       NaN      42.0
           docetaxel injection     Pressure         28.0      29.0      30.0
                                   Temperature      56.0      57.0      58.0
           ketamine hydrochloride  Pressure         16.0      17.0      18.0
                                   Temperature      13.0      14.0      15.0
17-10-2020 diltiazem hydrochloride Pressure         11.0      13.0      14.0
                                   Temperature      14.0      11.0      10.0
           docetaxel injection     Pressure         28.0      29.0      28.0
                                   Temperature      21.0      22.0      23.0
           ketamine hydrochloride  Pressure         13.0      14.0      15.0
                                   Temperature      22.0      23.0      24.0

Time                                            1:30:00  2:30:00  3:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        12.0     13.0      NaN
                                   Temperature     23.0     22.0      NaN
           docetaxel injection     Pressure         NaN     22.0     22.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         8.0      NaN      NaN
                                   Temperature     24.0      NaN      NaN
16-10-2020 diltiazem hydrochloride Pressure        18.0     19.0     20.0
                                   Temperature     34.0     35.0     36.0
           docetaxel injection     Pressure        23.0     24.0      NaN
                                   Temperature     46.0     47.0      NaN
           ketamine hydrochloride  Pressure        12.0     12.0     13.0
                                   Temperature      8.0      9.0     10.0
17-10-2020 diltiazem hydrochloride Pressure         3.0      4.0      4.0
                                   Temperature     20.0     19.0     19.0
           docetaxel injection     Pressure        20.0     22.0     22.0
                                   Temperature     12.0     13.0     14.0
           ketamine hydrochloride  Pressure         8.0      9.0     10.0
                                   Temperature     13.0     14.0     15.0

Time                                            4:30:00  5:30:00  6:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        11.0     13.0     14.0
                                   Temperature     21.0     21.0     22.0
           docetaxel injection     Pressure         NaN     22.0     23.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         7.0      NaN      9.0
                                   Temperature     27.0      NaN     26.0
16-10-2020 diltiazem hydrochloride Pressure        21.0     22.0     23.0
                                   Temperature     36.0     37.0     38.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     48.0     48.0     49.0
           ketamine hydrochloride  Pressure         NaN     15.0     15.0
                                   Temperature      NaN     11.0     12.0
17-10-2020 diltiazem hydrochloride Pressure         4.0      6.0      8.0
                                   Temperature     18.0     17.0     16.0
           docetaxel injection     Pressure        22.0     22.0     23.0
                                   Temperature     15.0     16.0     17.0
           ketamine hydrochloride  Pressure        11.0     11.0     12.0
                                   Temperature     16.0     17.0     18.0

Time                                            7:30:00  8:30:00  9:30:00
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        16.0     16.0     24.0
                                   Temperature     23.0     21.0     22.0
           docetaxel injection     Pressure         NaN      NaN     27.0
                                   Temperature      NaN      NaN     23.0
           ketamine hydrochloride  Pressure        10.0     11.0     10.0
                                   Temperature     25.0     24.0     23.0
16-10-2020 diltiazem hydrochloride Pressure        24.0     25.0     25.0
                                   Temperature     37.0     38.0     39.0
           docetaxel injection     Pressure        28.0     29.0     28.0
                                   Temperature     50.0     52.0     55.0
           ketamine hydrochloride  Pressure        15.0     15.0      NaN
                                   Temperature     12.0     11.0      NaN
17-10-2020 diltiazem hydrochloride Pressure         9.0      NaN      9.0
                                   Temperature     15.0      NaN     13.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     18.0     19.0     20.0
           ketamine hydrochloride  Pressure        12.0     11.0     12.0
                                   Temperature     19.0     20.0     21.0

In [ ]:
df_pivot = df_pivot.reset_index()

In [ ]:
df_pivot.columns

Index(['Date', 'Drug_Name', 'Parameter', '10:30:00', '11:30:00', '12:30:00',
       '1:30:00', '2:30:00', '3:30:00', '4:30:00', '5:30:00', '6:30:00',
       '7:30:00', '8:30:00', '9:30:00'],
      dtype='object', name='Time')

In [ ]:
df_pivot.columns.name

'Time'

In [ ]:
df_pivot.columns.name = None

In [ ]:
df_pivot

,Date,Drug_Name,Parameter,10:30:00,11:30:00,12:30:00,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00
0,15-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,12.0,13.0,NaN,11.0,13.0,14.0,16.0,16.0,24.0
1,15-10-2020,diltiazem hydrochloride,Temperature,20.0,20.0,21.0,23.0,22.0,NaN,21.0,21.0,22.0,23.0,21.0,22.0
2,15-10-2020,docetaxel injection,Pressure,26.0,29.0,28.0,NaN,22.0,22.0,NaN,22.0,23.0,NaN,NaN,27.0
3,15-10-2020,docetaxel injection,Temperature,23.0,25.0,25.0,NaN,17.0,18.0,NaN,17.0,18.0,NaN,NaN,23.0
4,15-10-2020,ketamine hydrochloride,Pressure,9.0,9.0,11.0,8.0,NaN,NaN,7.0,NaN,9.0,10.0,11.0,10.0
5,15-10-2020,ketamine hydrochloride,Temperature,22.0,21.0,20.0,24.0,NaN,NaN,27.0,NaN,26.0,25.0,24.0,23.0
6,16-10-2020,diltiazem hydrochloride,Pressure,24.0,NaN,27.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,25.0
7,16-10-2020,diltiazem hydrochloride,Temperature,40.0,NaN,42.0,34.0,35.0,36.0,36.0,37.0,38.0,37.0,38.0,39.0
8,16-10-2020,docetaxel injection,Pressure,28.0,29.0,30.0,23.0,24.0,NaN,25.0,26.0,27.0,28.0,29.0,28.0
9,16-10-2020,docetaxel injection,Temperature,56.0,57.0,58.0,46.0,47.0,NaN,48.0,48.0,49.0,50.0,52.0,55.0
10,16-10-2020,ketamine hydrochloride,Pressure,16.0,17.0,18.0,12.0,12.0,13.0,NaN,15.0,15.0,15.0,15.0,NaN
11,16-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,8.0,9.0,10.0,NaN,11.0,12.0,12.0,11.0,NaN
12,17-10-2020,diltiazem hydrochloride,Pressure,11.0,13.0,14.0,3.0,4.0,4.0,4.0,6.0,8.0,9.0,NaN,9.0
13,17-10-2020,diltiazem hydrochloride,Temperature,14.0,11.0,10.0,20.0,19.0,19.0,18.0,17.0,16.0,15.0,NaN,13.0
14,17-10-2020,docetaxel injection,Pressure,28.0,29.0,28.0,20.0,22.0,22.0,22.0,22.0,23.0,25.0,26.0,27.0
15,17-10-2020,docetaxel injection,Temperature,21.0,22.0,23.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0
16,17-10-2020,ketamine hydrochloride,Pressure,13.0,14.0,15.0,8.0,9.0,10.0,11.0,11.0,12.0,12.0,11.0,12.0
17,17-10-2020,ketamine hydrochloride,Temperature,22.0,23.0,24.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0

In [ ]:
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df_melt

           Date                Drug_Name    Parameter      Time  Result
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00    23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00    12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00     NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00     NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00    24.0
..          ...                      ...          ...       ...     ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00    14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00    23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00    28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00    24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00    15.0

[216 rows x 5 columns]

In [ ]:
df_tidy=pd.pivot(df_melt,
         index=["Date","Drug_Name","Time"],
         columns="Parameter",
         values="Result").reset_index()

In [ ]:
df_tidy

Parameter,Date,Drug_Name,Time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0
...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0

In [ ]:
df_tidy.columns.name

'Parameter'

In [ ]:
df_tidy.columns.name=None

In [ ]:
df_tidy

           Date                Drug_Name      Time  Pressure  Temperature
0    15-10-2020  diltiazem hydrochloride  10:30:00      18.0         20.0
1    15-10-2020  diltiazem hydrochloride  11:30:00      19.0         20.0
2    15-10-2020  diltiazem hydrochloride  12:30:00      20.0         21.0
3    15-10-2020  diltiazem hydrochloride   1:30:00      12.0         23.0
4    15-10-2020  diltiazem hydrochloride   2:30:00      13.0         22.0
..          ...                      ...       ...       ...          ...
103  17-10-2020   ketamine hydrochloride   5:30:00      11.0         17.0
104  17-10-2020   ketamine hydrochloride   6:30:00      12.0         18.0
105  17-10-2020   ketamine hydrochloride   7:30:00      12.0         19.0
106  17-10-2020   ketamine hydrochloride   8:30:00      11.0         20.0
107  17-10-2020   ketamine hydrochloride   9:30:00      12.0         21.0

[108 rows x 5 columns]

In [ ]:
df_tidy.columns

Index(['Date', 'Drug_Name', 'Time', 'Pressure', 'Temperature'], dtype='object')

In [ ]:
df_tidy

           Date                Drug_Name      Time  Pressure  Temperature
0    15-10-2020  diltiazem hydrochloride  10:30:00      18.0         20.0
1    15-10-2020  diltiazem hydrochloride  11:30:00      19.0         20.0
2    15-10-2020  diltiazem hydrochloride  12:30:00      20.0         21.0
3    15-10-2020  diltiazem hydrochloride   1:30:00      12.0         23.0
4    15-10-2020  diltiazem hydrochloride   2:30:00      13.0         22.0
..          ...                      ...       ...       ...          ...
103  17-10-2020   ketamine hydrochloride   5:30:00      11.0         17.0
104  17-10-2020   ketamine hydrochloride   6:30:00      12.0         18.0
105  17-10-2020   ketamine hydrochloride   7:30:00      12.0         19.0
106  17-10-2020   ketamine hydrochloride   8:30:00      11.0         20.0
107  17-10-2020   ketamine hydrochloride   9:30:00      12.0         21.0

[108 rows x 5 columns]

In [ ]:
#pivot table

In [ ]:
pd.pivot_table(df_tidy,index="Drug_Name", columns="Date", values=["Pressure","Temperature"], aggfunc="mean")

                          Pressure                       Temperature  \
Date                    15-10-2020 16-10-2020 17-10-2020  15-10-2020
Drug_Name
diltiazem hydrochloride  16.000000  22.545455   7.727273   21.454545
docetaxel injection      24.875000  27.000000  24.500000   20.750000
ketamine hydrochloride    9.333333  14.800000  11.500000   23.555556


Date                    16-10-2020 17-10-2020
Drug_Name
diltiazem hydrochloride  37.454545  15.636364
docetaxel injection      51.454545  17.500000
ketamine hydrochloride   11.500000  18.500000

In [ ]:
pd.pivot_table(df_tidy,index="Drug_Name", columns="Date", values=["Pressure","Temperature"], aggfunc=["mean","max"], margins=True)

                              mean                                   \
                          Pressure
Date                    15-10-2020 16-10-2020 17-10-2020        All
Drug_Name
diltiazem hydrochloride  16.000000  22.545455   7.727273  15.424242
docetaxel injection      24.875000  27.000000  24.500000  25.483871
ketamine hydrochloride    9.333333  14.800000  11.500000  11.935484
All                      16.392857  21.656250  14.771429  17.568421

                                                                      \
                        Temperature
Date                     15-10-2020 16-10-2020 17-10-2020        All
Drug_Name
diltiazem hydrochloride   21.454545  37.454545  15.636364  24.848485
docetaxel injection       20.750000  51.454545  17.500000  30.387097
ketamine hydrochloride    23.555556  11.500000  18.500000  17.709677
All                       21.928571  34.156250  17.257143  24.326316

                               max                                          \
                          Pressure                             Temperature
Date                    15-10-2020 16-10-2020 17-10-2020   All  15-10-2020
Drug_Name
diltiazem hydrochloride       24.0       27.0       14.0  27.0        23.0
docetaxel injection           29.0       30.0       29.0  30.0        25.0
ketamine hydrochloride        11.0       18.0       15.0  18.0        27.0
All                           29.0       30.0       29.0  30.0        27.0



Date                    16-10-2020 17-10-2020   All
Drug_Name
diltiazem hydrochloride       42.0       20.0  42.0
docetaxel injection           58.0       23.0  58.0
ketamine hydrochloride        15.0       24.0  27.0
All                           58.0       24.0  58.0

In [ ]:
pd.pivot_table(df_tidy,
         index=["Date","Drug_Name"],
         values=["Pressure","Temperature"],
         aggfunc="max",
              )

                                    Pressure  Temperature
Date       Drug_Name
15-10-2020 diltiazem hydrochloride      24.0         23.0
           docetaxel injection          29.0         25.0
           ketamine hydrochloride       11.0         27.0
16-10-2020 diltiazem hydrochloride      27.0         42.0
           docetaxel injection          30.0         58.0
           ketamine hydrochloride       18.0         15.0
17-10-2020 diltiazem hydrochloride      14.0         20.0
           docetaxel injection          29.0         23.0
           ketamine hydrochloride       15.0         24.0

In [ ]:
None

In [ ]:
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
type(np.nan)

float

In [ ]:
type(None)

NoneType

In [ ]:
pd.Series([1,np.nan,2])

0    1.0
1    NaN
2    2.0
dtype: float64

In [ ]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
a=pd.Series(["1",np.nan,"2",None])

In [ ]:
a

0       1
1     NaN
2       2
3    None
dtype: object

In [ ]:
type(a[1])

float

In [ ]:
type(a[3])

NoneType

In [ ]:
pd.Series(["1","np.nan","2",None])

0         1
1    np.nan
2         2
3      None
dtype: object

In [ ]:
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df.isna()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
3,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
5,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
3,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
5,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df2=pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=["A","B","C","D"])
df2

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df3=pd.DataFrame([["np.nan", 2, np.nan, 0],
                   ["3", 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   ["np.nan", 3, np.nan, 4]],
                  columns=["A","B","C","D"])
df3

        A    B   C    D
0  np.nan  2.0 NaN  0.0
1       3  4.0 NaN  1.0
2     NaN  NaN NaN  NaN
3  np.nan  3.0 NaN  4.0

In [ ]:
df2

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df2["A"].mean()

3.0

In [ ]:
df2.isna()

       A      B     C      D
0   True  False  True  False
1  False  False  True  False
2   True   True  True   True
3   True  False  True  False

In [ ]:
pd.isna #aliases

In [ ]:
pd.isnull #aliases

In [ ]:
df2

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df2.isna().sum(axis=1)

0    2
1    1
2    4
3    2
dtype: int64

In [ ]:
df2.isna().sum(axis=0)

A    3
B    1
C    4
D    1
dtype: int64

In [ ]:
df2["D"].mean()

1.6666666666666667

In [ ]:
5/3

1.6666666666666667

In [ ]:
#handle the missing data
#1. dropping
#2. Imputation

In [ ]:
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df2

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df2.fillna(df2["A"].mean())

     A    B    C    D
0  3.0  2.0  3.0  0.0
1  3.0  4.0  3.0  1.0
2  3.0  3.0  3.0  3.0
3  3.0  3.0  3.0  4.0

In [ ]:
df2["A"].fillna(df2["A"].mean())

0    3.0
1    3.0
2    3.0
3    3.0
Name: A, dtype: float64

In [ ]:
df2

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df2.fillna(method='ffill')

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [ ]:
df2

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [ ]:
df2.fillna(method='bfill')

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0

In [ ]:
df.isna().sum()

Date         0
Drug_Name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

In [ ]:
df.dropna() #axis=0

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df.shape

(18, 15)

In [ ]:
df.dropna(axis=1)

,Date,Drug_Name,Parameter,6:30:00,10:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,22,20,21
1,15-10-2020,diltiazem hydrochloride,Pressure,14,18,20
2,15-10-2020,docetaxel injection,Temperature,18,23,25
3,15-10-2020,docetaxel injection,Pressure,23,26,28
4,15-10-2020,ketamine hydrochloride,Temperature,26,22,20
5,15-10-2020,ketamine hydrochloride,Pressure,9,9,11
6,16-10-2020,diltiazem hydrochloride,Temperature,38,40,42
7,16-10-2020,diltiazem hydrochloride,Pressure,23,24,27
8,16-10-2020,docetaxel injection,Temperature,49,56,58
9,16-10-2020,docetaxel injection,Pressure,27,28,30
10,16-10-2020,ketamine hydrochloride,Temperature,12,13,15
11,16-10-2020,ketamine hydrochloride,Pressure,15,16,18
12,17-10-2020,diltiazem hydrochloride,Temperature,16,14,10
13,17-10-2020,diltiazem hydrochloride,Pressure,8,11,14
14,17-10-2020,docetaxel injection,Temperature,17,21,23
15,17-10-2020,docetaxel injection,Pressure,23,28,28
16,17-10-2020,ketamine hydrochloride,Temperature,18,22,24
17,17-10-2020,ketamine hydrochloride,Pressure,12,13,15

In [ ]:
df.fillna(0)

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,0.0,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,0.0,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,0.0,17.0,18.0,0.0,17.0,18,0.0,0.0,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,0.0,22.0,22.0,0.0,22.0,23,0.0,0.0,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,0.0,0.0,27.0,0.0,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,0.0,0.0,7.0,0.0,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,0.0,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,0.0,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,0.0,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,0.0,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,0.0,11.0,12,12.0,11.0,0.0,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,0.0,15.0,15,15.0,15.0,0.0,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,0.0,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,0.0,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
df['1:30:00'].fillna(df['1:30:00'].mean())

0     23.00
1     12.00
2     17.75
3     17.75
4     24.00
5      8.00
6     34.00
7     18.00
8     46.00
9     23.00
10     8.00
11    12.00
12    20.00
13     3.00
14    12.00
15    20.00
16    13.00
17     8.00
Name: 1:30:00, dtype: float64

In [ ]:
df.iloc[0,3:].mean().round(1)

21.5

In [ ]:
df.iloc[0].fillna(df.iloc[0,3:].mean().round(1))

Date                      15-10-2020
Drug_Name    diltiazem hydrochloride
Parameter                Temperature
1:30:00                         23.0
2:30:00                         22.0
3:30:00                         21.5
4:30:00                         21.0
5:30:00                         21.0
6:30:00                           22
7:30:00                         23.0
8:30:00                         21.0
9:30:00                         22.0
10:30:00                          20
11:30:00                        20.0
12:30:00                          21
Name: 0, dtype: object

In [ ]:
df_tidy.head(20)

          Date                Drug_Name      Time  Pressure  Temperature
0   15-10-2020  diltiazem hydrochloride  10:30:00      18.0         20.0
1   15-10-2020  diltiazem hydrochloride  11:30:00      19.0         20.0
2   15-10-2020  diltiazem hydrochloride  12:30:00      20.0         21.0
3   15-10-2020  diltiazem hydrochloride   1:30:00      12.0         23.0
4   15-10-2020  diltiazem hydrochloride   2:30:00      13.0         22.0
5   15-10-2020  diltiazem hydrochloride   3:30:00       NaN          NaN
6   15-10-2020  diltiazem hydrochloride   4:30:00      11.0         21.0
7   15-10-2020  diltiazem hydrochloride   5:30:00      13.0         21.0
8   15-10-2020  diltiazem hydrochloride   6:30:00      14.0         22.0
9   15-10-2020  diltiazem hydrochloride   7:30:00      16.0         23.0
10  15-10-2020  diltiazem hydrochloride   8:30:00      16.0         21.0
11  15-10-2020  diltiazem hydrochloride   9:30:00      24.0         22.0
12  15-10-2020      docetaxel injection  10:30:00      26.0         23.0
13  15-10-2020      docetaxel injection  11:30:00      29.0         25.0
14  15-10-2020      docetaxel injection  12:30:00      28.0         25.0
15  15-10-2020      docetaxel injection   1:30:00       NaN          NaN
16  15-10-2020      docetaxel injection   2:30:00      22.0         17.0
17  15-10-2020      docetaxel injection   3:30:00      22.0         18.0
18  15-10-2020      docetaxel injection   4:30:00       NaN          NaN
19  15-10-2020      docetaxel injection   5:30:00      22.0         17.0

In [ ]:
#custom functions

def temp_mean(x):
    x["Temp_avg"]=np.round(x["Temperature"].mean(),2)
    return x

In [ ]:
df_tidy = df_tidy.groupby("Drug_Name").apply(temp_mean)
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85
...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71

In [ ]:
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85
...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71

In [ ]:
#ignore warnings code
import warnings
warnings.filterwarnings("ignore")

df_tidy=df_tidy.groupby("Drug_Name").apply(temp_mean)
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85
...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71

In [ ]:
df_tidy["Temperature"].fillna(df_tidy["Temp_avg"],inplace=True)

In [ ]:
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85
...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71

In [ ]:
def pres_mean(x):
    x["Pres_avg"]=np.round(x["Pressure"].mean(),2)
    return x

In [ ]:
df_tidy=df_tidy.groupby("Drug_Name").apply(pres_mean)

df_tidy["Pressure"].fillna(df_tidy["Pres_avg"],inplace=True)
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg,Pres_avg
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85,15.42
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85,15.42
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85,15.42
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85,15.42
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85,15.42
...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71,11.94
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71,11.94
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71,11.94
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71,11.94
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71,11.94

In [ ]:
df_tidy["Temperature"].max()

58.0

In [ ]:
df_tidy["Temperature"].min()

8.0

In [ ]:
temp_points=[7,20,24,27,58]
temp_labels=["low","medium","high","very_high"]

df_tidy["Temp_cat"]=pd.cut(df_tidy["Temperature"],
                          bins=temp_points,
                          labels=temp_labels)
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg,Pres_avg,Temp_cat
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85,15.42,low
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85,15.42,low
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85,15.42,medium
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85,15.42,medium
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85,15.42,medium
...,...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71,11.94,low
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71,11.94,low
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71,11.94,low
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71,11.94,low
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71,11.94,medium

In [ ]:
df_tidy["Temp_cat"].value_counts()

low          50
very_high    27
medium       23
high          8
Name: Temp_cat, dtype: int64

In [ ]:
df_tidy.loc[df_tidy["Drug_Name"]=="hydrochloride"]

Empty DataFrame
Columns: [Date, Drug_Name, Time, Pressure, Temperature, Temp_avg, Pres_avg, Temp_cat]
Index: []

In [ ]:
df_tidy["Drug_Name"].str.contains("hydrochloride")

0      True
1      True
2      True
3      True
4      True
       ...
103    True
104    True
105    True
106    True
107    True
Name: Drug_Name, Length: 108, dtype: bool

In [ ]:
df_tidy.loc[df_tidy["Drug_Name"].str.contains("hydrochloride")]

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg,Pres_avg,Temp_cat
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85,15.42,low
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85,15.42,low
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85,15.42,medium
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85,15.42,medium
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85,15.42,medium
...,...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71,11.94,low
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71,11.94,low
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71,11.94,low
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71,11.94,low
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71,11.94,medium

In [ ]:
#handle time and date info

In [ ]:
df_tidy["Date"]

0      15-10-2020
1      15-10-2020
2      15-10-2020
3      15-10-2020
4      15-10-2020
          ...
103    17-10-2020
104    17-10-2020
105    17-10-2020
106    17-10-2020
107    17-10-2020
Name: Date, Length: 108, dtype: object

In [ ]:
df_tidy["Date"].str.split("-")

0      [15, 10, 2020]
1      [15, 10, 2020]
2      [15, 10, 2020]
3      [15, 10, 2020]
4      [15, 10, 2020]
            ...
103    [17, 10, 2020]
104    [17, 10, 2020]
105    [17, 10, 2020]
106    [17, 10, 2020]
107    [17, 10, 2020]
Name: Date, Length: 108, dtype: object

In [ ]:
df_tidy["Date"].str.split("-").str[-1]

0      2020
1      2020
2      2020
3      2020
4      2020
       ...
103    2020
104    2020
105    2020
106    2020
107    2020
Name: Date, Length: 108, dtype: object

In [ ]:
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg,Pres_avg,Temp_cat
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85,15.42,low
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85,15.42,low
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85,15.42,medium
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85,15.42,medium
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85,15.42,medium
...,...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71,11.94,low
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71,11.94,low
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71,11.94,low
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71,11.94,low
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71,11.94,medium

In [ ]:
df_tidy["timestamp"]=df_tidy["Date"]+" "+df_tidy["Time"]

In [ ]:
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_avg,Pres_avg,Temp_cat,timestamp
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.85,15.42,low,15-10-2020 10:30:00
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.85,15.42,low,15-10-2020 11:30:00
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.85,15.42,medium,15-10-2020 12:30:00
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.85,15.42,medium,15-10-2020 1:30:00
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.85,15.42,medium,15-10-2020 2:30:00
...,...,...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.71,11.94,low,17-10-2020 5:30:00
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.71,11.94,low,17-10-2020 6:30:00
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.71,11.94,low,17-10-2020 7:30:00
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.71,11.94,low,17-10-2020 8:30:00
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.71,11.94,medium,17-10-2020 9:30:00

In [ ]:
df_tidy.drop(columns=["Pres_avg","Temp_avg"], inplace=True)

In [ ]:
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_cat,timestamp
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,low,15-10-2020 10:30:00
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,low,15-10-2020 11:30:00
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,medium,15-10-2020 12:30:00
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,medium,15-10-2020 1:30:00
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,medium,15-10-2020 2:30:00
...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,low,17-10-2020 5:30:00
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,low,17-10-2020 6:30:00
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,low,17-10-2020 7:30:00
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,low,17-10-2020 8:30:00
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,medium,17-10-2020 9:30:00

In [ ]:
df_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         108 non-null    object
 1   Drug_Name    108 non-null    object
 2   Time         108 non-null    object
 3   Pressure     108 non-null    float64
 4   Temperature  108 non-null    float64
 5   Temp_cat     108 non-null    category
 6   timestamp    108 non-null    object
dtypes: category(1), float64(2), object(4)
memory usage: 10.3+ KB

In [ ]:
df_tidy["timestamp"]=pd.to_datetime(df_tidy["timestamp"])
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_cat,timestamp
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,low,2020-10-15 10:30:00
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,low,2020-10-15 11:30:00
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,medium,2020-10-15 12:30:00
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,medium,2020-10-15 01:30:00
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,medium,2020-10-15 02:30:00
...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,low,2020-10-17 05:30:00
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,low,2020-10-17 06:30:00
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,low,2020-10-17 07:30:00
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,low,2020-10-17 08:30:00
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,medium,2020-10-17 09:30:00

In [ ]:
df_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         108 non-null    object
 1   Drug_Name    108 non-null    object
 2   Time         108 non-null    object
 3   Pressure     108 non-null    float64
 4   Temperature  108 non-null    float64
 5   Temp_cat     108 non-null    category
 6   timestamp    108 non-null    datetime64[ns]
dtypes: category(1), datetime64[ns](1), float64(2), object(3)
memory usage: 10.3+ KB

In [ ]:
ts = df_tidy["timestamp"][0]
ts

Timestamp('2020-10-15 10:30:00')

In [ ]:
type(ts)

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
ts.year

2020

In [ ]:
ts.month

10

In [ ]:
ts.day

15

In [ ]:
ts.month_name()

'October'

In [ ]:
ts.day_name()

'Thursday'

In [ ]:
ts.day_of_week

3

In [ ]:
ts.hour

10

In [ ]:
ts.minute

30

In [ ]:
ts.second

0

In [ ]:
ts.microsecond

0

In [ ]:
ts.nanosecond

0

In [ ]:
ts.picosecond

AttributeError: ignored

In [ ]:
df_tidy["timestamp"].dt

In [ ]:
df_tidy["timestamp"].dt.year

0      2020
1      2020
2      2020
3      2020
4      2020
       ...
103    2020
104    2020
105    2020
106    2020
107    2020
Name: timestamp, Length: 108, dtype: int64

In [ ]:
df_tidy["timestamp"].dt.month

0      10
1      10
2      10
3      10
4      10
       ..
103    10
104    10
105    10
106    10
107    10
Name: timestamp, Length: 108, dtype: int64

In [ ]:
df_tidy["timestamp"].dt.day

0      15
1      15
2      15
3      15
4      15
       ..
103    17
104    17
105    17
106    17
107    17
Name: timestamp, Length: 108, dtype: int64

In [ ]:
#get the output in a particular format

In [ ]:
df_tidy["timestamp"][0].strftime("%Y-%m-%d")

'2020-10-15'

In [ ]:
df_tidy["timestamp"][0].strftime("%d-%m-%Y")

'15-10-2020'

In [ ]:
df_tidy["timestamp"][0].strftime("%H-%M-%S")

'10-30-00'

In [ ]:
df_tidy["timestamp"][0].strftime("%b %d,%Y") #b is for month

'Oct 15,2020'

In [ ]:
df_tidy["timestamp"][0].strftime("%B %d,%Y")

'October 15,2020'

In [ ]:
df_tidy

,Date,Drug_Name,Time,Pressure,Temperature,Temp_cat,timestamp
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,low,2020-10-15 10:30:00
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,low,2020-10-15 11:30:00
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,medium,2020-10-15 12:30:00
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,medium,2020-10-15 01:30:00
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,medium,2020-10-15 02:30:00
...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,low,2020-10-17 05:30:00
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,low,2020-10-17 06:30:00
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,low,2020-10-17 07:30:00
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,low,2020-10-17 08:30:00
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,medium,2020-10-17 09:30:00

In [ ]:
df_tidy.to_csv("drug_clean_data_dirty.csv",sep=",")