<a href="https://colab.research.google.com/github/shashank89-it/colab/blob/main/Pandas_Lec1_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
import pandas as pd
df = pd.read_csv("mckinsey.csv")
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.rename({"country":"Country"}, axis=1)

          Country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.rename({"country":"Country"}, axis=1, inplace=True)

In [ ]:
df

          Country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.rename(columns={"life_exp":"Life_exp",
                   "population":"Population",
                   "continent":"Continent"},inplace=True)
df

          Country  year  Population Continent  Life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.columns[-1]

'gdp_cap'

In [ ]:
#drop

In [ ]:
df.drop("Country",axis=1)

      year  Population Continent  Life_exp     gdp_cap
0     1952     8425333      Asia    28.801  779.445314
1     1957     9240934      Asia    30.332  820.853030
2     1962    10267083      Asia    31.997  853.100710
3     1967    11537966      Asia    34.020  836.197138
4     1972    13079460      Asia    36.088  739.981106
...    ...         ...       ...       ...         ...
1699  1987     9216418    Africa    62.351  706.157306
1700  1992    10704340    Africa    60.377  693.420786
1701  1997    11404948    Africa    46.809  792.449960
1702  2002    11926563    Africa    39.989  672.038623
1703  2007    12311143    Africa    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.drop(["Country","year"],axis=1)

      Population Continent  Life_exp     gdp_cap
0        8425333      Asia    28.801  779.445314
1        9240934      Asia    30.332  820.853030
2       10267083      Asia    31.997  853.100710
3       11537966      Asia    34.020  836.197138
4       13079460      Asia    36.088  739.981106
...          ...       ...       ...         ...
1699     9216418    Africa    62.351  706.157306
1700    10704340    Africa    60.377  693.420786
1701    11404948    Africa    46.809  792.449960
1702    11926563    Africa    39.989  672.038623
1703    12311143    Africa    43.487  469.709298

[1704 rows x 4 columns]

In [ ]:
df.drop(["Country","year"],axis=0)

KeyError: ignored

In [ ]:
df

          Country  year  Population Continent  Life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.drop(df.columns[-1],axis=1)

          Country  year  Population Continent  Life_exp
0     Afghanistan  1952     8425333      Asia    28.801
1     Afghanistan  1957     9240934      Asia    30.332
2     Afghanistan  1962    10267083      Asia    31.997
3     Afghanistan  1967    11537966      Asia    34.020
4     Afghanistan  1972    13079460      Asia    36.088
...           ...   ...         ...       ...       ...
1699     Zimbabwe  1987     9216418    Africa    62.351
1700     Zimbabwe  1992    10704340    Africa    60.377
1701     Zimbabwe  1997    11404948    Africa    46.809
1702     Zimbabwe  2002    11926563    Africa    39.989
1703     Zimbabwe  2007    12311143    Africa    43.487

[1704 rows x 5 columns]

In [ ]:
#Add columns

In [ ]:
df

          Country  year  Population Continent  Life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df["year+7"] = df["year"]+7

In [ ]:
df

          Country  year  Population Continent  Life_exp     gdp_cap  year+7
0     Afghanistan  1952     8425333      Asia    28.801  779.445314    1959
1     Afghanistan  1957     9240934      Asia    30.332  820.853030    1964
2     Afghanistan  1962    10267083      Asia    31.997  853.100710    1969
3     Afghanistan  1967    11537966      Asia    34.020  836.197138    1974
4     Afghanistan  1972    13079460      Asia    36.088  739.981106    1979
...           ...   ...         ...       ...       ...         ...     ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306    1994
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786    1999
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960    2004
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623    2009
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298    2014

[1704 rows x 7 columns]

In [ ]:
df["year + gdp_cap"] =  ( df["year"] + df["gdp_cap"] )*2

In [ ]:
df

,Country,year,Population,Continent,Life_exp,gdp_cap,year+7,year + gdp_cap
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,1959,5462.890629
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,1964,5555.706059
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,1969,5630.201420
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,1974,5606.394276
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,1979,5423.962212
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1994,5386.314612
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1999,5370.841571
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,2004,5578.899921
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,2009,5348.077245
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,2014,4953.418596

In [ ]:
df.columns

Index(['Country', 'year', 'Population', 'Continent', 'Life_exp', 'gdp_cap',
       'year+7', 'year + gdp_cap'],
      dtype='object')

In [ ]:
df["own"]=[i for i in range(1,df.shape[0]+1)]

In [ ]:
df

,Country,year,Population,Continent,Life_exp,gdp_cap,year+7,year + gdp_cap,own
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,1959,5462.890629,1
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,1964,5555.706059,2
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,1969,5630.201420,3
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,1974,5606.394276,4
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,1979,5423.962212,5
...,...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1994,5386.314612,1700
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1999,5370.841571,1701
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,2004,5578.899921,1702
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,2009,5348.077245,1703
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,2014,4953.418596,1704

In [ ]:
df.shape

(1704, 9)

In [ ]:
df.shape[0]

1704

In [ ]:
#Working with Rows. #re-loaded data

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.head(1)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314

In [ ]:
#df[0]

In [ ]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [ ]:
df.index[0]

0

In [ ]:
df2 = df.head(5)

In [ ]:
df2

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df2.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df2.index = [1,2,3,4,5] #integers
df2

       country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1967    11537966      Asia    34.020  836.197138
5  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df2.index = [1.0,2.0,3.0,4.0,5.0]
df2

         country  year  population continent  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333      Asia    28.801  779.445314
2.0  Afghanistan  1957     9240934      Asia    30.332  820.853030
3.0  Afghanistan  1962    10267083      Asia    31.997  853.100710
4.0  Afghanistan  1967    11537966      Asia    34.020  836.197138
5.0  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df2.index = ['a','b','c','d','e']
df2

       country  year  population continent  life_exp     gdp_cap
a  Afghanistan  1952     8425333      Asia    28.801  779.445314
b  Afghanistan  1957     9240934      Asia    30.332  820.853030
c  Afghanistan  1962    10267083      Asia    31.997  853.100710
d  Afghanistan  1967    11537966      Asia    34.020  836.197138
e  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
ser=pd.Series(['a','b','c','d','e','f','g','h'])
ser

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
dtype: object

In [ ]:
ser2=pd.Series(['a','b','c','d','e','f','g','h'],index=[1,2,3,4,5,6,7,8])
ser2

1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object

In [ ]:
ser #implicit indexes

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
dtype: object

In [ ]:
ser[0]

'a'

In [ ]:
ser[2:6]

2    c
3    d
4    e
5    f
dtype: object

In [ ]:
ser2 #explicit indexes

1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object

In [ ]:
ser2[1] #indexing

'a'

In [ ]:
ser2

1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object

In [ ]:
ser2[3:7] #slicing #refers to implicit #not to be used

4    d
5    e
6    f
7    g
dtype: object

In [ ]:
#Solution : iloc and loc

In [ ]:
# ser.loc[] # always take explicit #it takes the last value (inclusive)

# ser.iloc[] # integer based locking is iloc. #always takes implicit

In [ ]:
ser

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
dtype: object

In [ ]:
ser.iloc[4]

'e'

In [ ]:
ser.iloc[2:6]

2    c
3    d
4    e
5    f
dtype: object

In [ ]:
ser

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
dtype: object

In [ ]:
ser.loc[4]

'e'

In [ ]:
ser.loc[2:6]

2    c
3    d
4    e
5    f
6    g
dtype: object

In [ ]:
ser2

1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object

In [ ]:
ser2.loc[2]

'b'

In [ ]:
ser2.loc[2:6]

2    b
3    c
4    d
5    e
6    f
dtype: object

In [ ]:
ser2

1    a
2    b
3    c
4    d
5    e
6    f
7    g
8    h
dtype: object

In [ ]:
ser2.iloc[1]

'b'

In [ ]:
ser2.iloc[2:6]

3    c
4    d
5    e
6    f
dtype: object

In [ ]:
ser3=pd.Series(['a','b','c','d','e','f','g','h'],index=['b','c','d','e','f','g','h',"i"])
ser3

b    a
c    b
d    c
e    d
f    e
g    f
h    g
i    h
dtype: object

In [ ]:
ser3.loc["e"]

'd'

In [ ]:
ser3.iloc["e"]

TypeError: ignored

In [ ]:
ser3

b    a
c    b
d    c
e    d
f    e
g    f
h    g
i    h
dtype: object

In [ ]:
ser3.iloc[4]

'e'

In [ ]:
ser3.loc["c":"h"]

c    b
d    c
e    d
f    e
g    f
h    g
dtype: object

In [ ]:
ser3

b    a
c    b
d    c
e    d
f    e
g    f
h    g
i    h
dtype: object

In [ ]:
ser3.loc["c":"h":2]

c    b
e    d
g    f
dtype: object

In [ ]:
ser3.iloc[1:7]

c    b
d    c
e    d
f    e
g    f
h    g
dtype: object