<a href="https://colab.research.google.com/github/shashank89-it/colab/blob/main/Pandas_Lec_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Agenda
- **Feature Exploration**
    - Create new features

- **Fetching data using pandas**
    - Quering from dataframe - Masking, Filtering, `&` and `|`

- **Apply**

- **Grouping**
    - Split, Apply, Combine
    - `groupby()`
- **Group based Aggregates**

- **Group based Filtering**

- **Group based Transformation**
    - `apply()`

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
movies = pd.read_csv("/content/movies.csv")
movies

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [ ]:
directors = pd.read_csv("/content/directors.csv")
directors

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [ ]:
directors.drop(columns="Unnamed: 0",inplace=True)
directors

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

In [ ]:
movies.drop(columns=["Unnamed: 0"],inplace=True)
movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0,25.29,25.29
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0,6.87,6.87
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0,-3.00,-3.00
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0,0.00,0.00
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0,3.94,3.94

In [ ]:
data=pd.merge(movies,directors,left_on="director_id",right_on="id",how="inner")

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,4762,1997,Nov,Tuesday,James Cameron,4762,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,4762,1991,Jul,Monday,James Cameron,4762,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,4762,1994,Jul,Thursday,James Cameron,4762,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,4762,1989,Aug,Wednesday,James Cameron,4762,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,6204,2013,Sep,Wednesday,Nicole Holofcener,6204,Female
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,6204,2006,Sep,Thursday,Nicole Holofcener,6204,Female
1462,47524,3000000,5,0,Please Give,6.0,57,6204,2010,Jan,Friday,Nicole Holofcener,6204,Female
1463,47962,0,0,0,Walking and Talking,6.6,7,6204,1996,Jul,Wednesday,Nicole Holofcener,6204,Female
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,6204,2001,Aug,Friday,Nicole Holofcener,6204,Female

In [ ]:
data.drop(columns=["director_id","id_y"],inplace=True)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_x           1465 non-null   int64
 1   budget         1465 non-null   int64
 2   popularity     1465 non-null   int64
 3   revenue        1465 non-null   int64
 4   title          1465 non-null   object
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64
 7   year           1465 non-null   int64
 8   month          1465 non-null   object
 9   day            1465 non-null   object
 10  director_name  1465 non-null   object
 11  gender         1341 non-null   object
dtypes: float64(1), int64(6), object(5)
memory usage: 148.8+ KB

In [ ]:
data.describe(include="all")

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
count,1465.000000,1.465000e+03,1465.000000,1.465000e+03,1465,1465.000000,1465.000000,1465.000000,1465,1465,1465,1341
unique,NaN,NaN,NaN,NaN,1465,NaN,NaN,NaN,12,7,199,2
top,NaN,NaN,NaN,NaN,Avatar,NaN,NaN,NaN,Dec,Friday,Steven Spielberg,Male
freq,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,193,654,26,1309
mean,45225.191126,4.802295e+07,30.855973,1.432539e+08,NaN,6.368191,1146.396587,2002.615017,NaN,NaN,NaN,NaN
std,1189.096396,4.935541e+07,34.845214,2.064918e+08,NaN,0.818033,1578.077438,8.680141,NaN,NaN,NaN,NaN
min,43597.000000,0.000000e+00,0.000000,0.000000e+00,NaN,3.000000,1.000000,1976.000000,NaN,NaN,NaN,NaN
25%,44236.000000,1.400000e+07,11.000000,1.738013e+07,NaN,5.900000,216.000000,1998.000000,NaN,NaN,NaN,NaN
50%,45022.000000,3.300000e+07,23.000000,7.578164e+07,NaN,6.400000,571.000000,2004.000000,NaN,NaN,NaN,NaN
75%,45990.000000,6.600000e+07,41.000000,1.792469e+08,NaN,6.900000,1387.000000,2009.000000,NaN,NaN,NaN,NaN
max,48395.000000,3.800000e+08,724.000000,2.787965e+09,NaN,8.300000,13752.000000,2016.000000,NaN,NaN,NaN,NaN

In [ ]:
data["revenue"]=(data["revenue"]/1000000).round(2)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female
1461,47023,6500000,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female
1462,47524,3000000,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1463,47962,0,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female
1464,48229,250000,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [ ]:
data["budget"]= (data["budget"]/1000000).round(2)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [ ]:
#problem stmt : Get the highest rated movies where rating > 7

In [ ]:
data["vote_average"]>7

0        True
1        True
2        True
3       False
4        True
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: vote_average, Length: 1465, dtype: bool

In [ ]:
data[data["vote_average"]>7]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
5,46000,18.50,67,183.32,Aliens,7.7,3220,1986,Jul,Friday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1424,47488,4.00,11,35.56,Bowling for Columbine,7.3,453,2002,Oct,Wednesday,Michael Moore,Male
1426,48310,0.16,3,6.71,Roger & Me,7.4,90,1989,Sep,Friday,Michael Moore,Male
1433,46168,11.50,15,23.24,The Remains of the Day,7.5,202,1993,Nov,Friday,James Ivory,Male
1438,47597,0.00,11,0.00,Maurice,7.1,61,1987,Sep,Friday,James Ivory,Male
1441,47232,5.00,35,8.20,The Machinist,7.3,1247,2004,Feb,Monday,Brad Anderson,Male

In [ ]:
data.loc[data["vote_average"]>7] #recommended

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
5,46000,18.50,67,183.32,Aliens,7.7,3220,1986,Jul,Friday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1424,47488,4.00,11,35.56,Bowling for Columbine,7.3,453,2002,Oct,Wednesday,Michael Moore,Male
1426,48310,0.16,3,6.71,Roger & Me,7.4,90,1989,Sep,Friday,Michael Moore,Male
1433,46168,11.50,15,23.24,The Remains of the Day,7.5,202,1993,Nov,Friday,James Ivory,Male
1438,47597,0.00,11,0.00,Maurice,7.1,61,1987,Sep,Friday,James Ivory,Male
1441,47232,5.00,35,8.20,The Machinist,7.3,1247,2004,Feb,Monday,Brad Anderson,Male

In [ ]:
data.loc[data["vote_average"]>7,["title","director_name"]]

                           title  director_name
0                         Avatar  James Cameron
1                        Titanic  James Cameron
2     Terminator 2: Judgment Day  James Cameron
4                      The Abyss  James Cameron
5                         Aliens  James Cameron
...                          ...            ...
1424       Bowling for Columbine  Michael Moore
1426                  Roger & Me  Michael Moore
1433      The Remains of the Day    James Ivory
1438                     Maurice    James Ivory
1441               The Machinist  Brad Anderson

[301 rows x 2 columns]

In [ ]:
#problem stmt : We want to return all the high rated movies on or after 2015

In [ ]:
data.loc[(data["vote_average"]>7) & (data["year"]>=2015)]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
93,43867,108.0,167,630.16,The Martian,7.6,7268,2015,Sep,Wednesday,Ridley Scott,Male
166,43641,190.0,102,1506.25,Furious 7,7.3,4176,2015,Apr,Wednesday,James Wan,Male
201,44784,40.0,48,165.48,Bridge of Spies,7.2,2583,2015,Oct,Thursday,Steven Spielberg,Male
361,43724,150.0,434,378.86,Mad Max: Fury Road,7.2,9427,2015,May,Wednesday,George Miller,Male
465,43773,135.0,100,532.95,The Revenant,7.3,6396,2015,Dec,Friday,Alejandro González Iñárritu,Male
512,44128,75.0,48,108.15,The Man from U.N.C.L.E.,7.1,2265,2015,Aug,Thursday,Guy Ritchie,Male
639,45301,28.0,57,133.35,The Big Short,7.3,2607,2015,Dec,Friday,Adam McKay,Male
649,44281,44.0,68,155.76,The Hateful Eight,7.6,4274,2015,Dec,Friday,Quentin Tarantino,Male
766,44770,35.0,53,194.56,The Intern,7.1,1881,2015,Sep,Thursday,Nancy Meyers,Female
818,47181,5.0,22,24.80,Race,7.1,478,2016,Feb,Friday,Stephen Hopkins,Male
853,45293,28.0,61,201.63,Straight Outta Compton,7.7,1355,2015,Aug,Thursday,F. Gary Gray,Male
861,45194,30.0,65,91.71,Southpaw,7.3,2067,2015,Jun,Monday,Antoine Fuqua,Male

In [ ]:
data.loc[(data["day"]=="Friday") | (data["day"]=="Saturday")]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
5,46000,18.50,67,183.32,Aliens,7.7,3220,1986,Jul,Friday,James Cameron,Male
6,47036,6.40,74,78.37,The Terminator,7.3,4128,1984,Oct,Friday,James Cameron,Male
7,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
16,44041,80.00,49,181.00,Road to Perdition,7.3,1077,2002,Jul,Friday,Sam Mendes,Male
17,44154,72.00,32,96.89,Jarhead,6.6,765,2005,Nov,Friday,Sam Mendes,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1455,46574,10.00,33,163.88,Saw III,6.1,1071,2006,Oct,Friday,Darren Lynn Bousman,Male
1457,46827,0.00,5,0.19,Repo! The Genetic Opera,6.7,100,2008,Jul,Friday,Darren Lynn Bousman,Male
1458,47152,4.00,42,152.93,Saw II,6.3,1251,2005,Oct,Friday,Darren Lynn Bousman,Male
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [ ]:
#top 5 popular movies

In [ ]:
data.sort_values(by=["popularity"],ascending=False).head(5)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
23,43692,165.0,724,675.12,Interstellar,8.1,10867,2014,Nov,Wednesday,Christopher Nolan,Male
361,43724,150.0,434,378.86,Mad Max: Fury Road,7.2,9427,2015,May,Wednesday,George Miller,Male
11,43796,140.0,271,655.01,Pirates of the Caribbean: The Curse of the Bla...,7.5,6985,2003,Jul,Wednesday,Gore Verbinski,Male
315,43797,125.0,206,752.10,The Hunger Games: Mockingjay - Part 1,6.6,5584,2014,Nov,Tuesday,Francis Lawrence,Male
22,43662,185.0,187,1004.56,The Dark Knight,8.2,12002,2008,Jul,Wednesday,Christopher Nolan,Male

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [ ]:
#Find all the movies by christopher nolan

In [ ]:
data.loc[data["director_name"]=="Christopher Nolan"]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
21,43600,250.0,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
22,43662,185.0,187,1004.56,The Dark Knight,8.2,12002,2008,Jul,Wednesday,Christopher Nolan,Male
23,43692,165.0,724,675.12,Interstellar,8.1,10867,2014,Nov,Wednesday,Christopher Nolan,Male
24,43693,160.0,167,825.53,Inception,8.1,13752,2010,Jul,Wednesday,Christopher Nolan,Male
25,43716,150.0,115,374.22,Batman Begins,7.5,7359,2005,Jun,Friday,Christopher Nolan,Male
26,44630,46.0,41,113.71,Insomnia,6.8,1148,2002,May,Friday,Christopher Nolan,Male
27,44793,40.0,74,109.68,The Prestige,8.0,4391,2006,Oct,Thursday,Christopher Nolan,Male
28,47170,9.0,60,39.72,Memento,8.1,4028,2000,Oct,Wednesday,Christopher Nolan,Male

In [ ]:
data.loc[data["director_name"]=="Christopher Nolan", ["title","year"]]

                    title  year
21  The Dark Knight Rises  2012
22        The Dark Knight  2008
23           Interstellar  2014
24              Inception  2010
25          Batman Begins  2005
26               Insomnia  2002
27           The Prestige  2006
28                Memento  2000

In [ ]:
#Apply method -- convert genders to 1 or 0

In [ ]:
def myfunc(data):
    if data =="Male":
        return 1
    elif data=="Female":
        return 0
    else:
        return np.nan

In [ ]:
data["gender"] = data["gender"].apply(myfunc)
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_x           1465 non-null   int64
 1   budget         1465 non-null   int64
 2   popularity     1465 non-null   int64
 3   revenue        1465 non-null   int64
 4   title          1465 non-null   object
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64
 7   year           1465 non-null   int64
 8   month          1465 non-null   object
 9   day            1465 non-null   object
 10  director_name  1465 non-null   object
 11  gender         1341 non-null   float64
dtypes: float64(2), int64(6), object(4)
memory usage: 148.8+ KB

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0

In [ ]:
data["profit_method_1"]=data["revenue"]-data["budget"]
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0,25.29
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0,6.87
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0,-3.00
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0,0.00
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0,3.94

In [ ]:
def profit_func(x):
    return x["revenue"]-x["budget"]

In [ ]:
data["method2"] = data[["revenue","budget"]].apply(profit_func,axis=1)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0,25.29,25.29
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0,6.87,6.87
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0,-3.00,-3.00
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0,0.00,0.00
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0,3.94,3.94

In [ ]:
#ufuncs

In [ ]:
data[["revenue","budget"]].apply(np.sum,axis=1)

0       3024.97
1       2045.03
2        620.00
3        493.88
4        160.00
         ...
1460      25.29
1461      19.87
1462       3.00
1463       0.00
1464       4.44
Length: 1465, dtype: float64

In [ ]:
data[["revenue","budget"]].apply(np.sum,axis=0)

revenue    209867.04
budget      70353.62
dtype: float64

In [ ]:
data[["revenue","budget"]]

      revenue  budget
0     2787.97  237.00
1     1845.03  200.00
2      520.00  100.00
3      378.88  115.00
4       90.00   70.00
...       ...     ...
1460    25.29    0.00
1461    13.37    6.50
1462     0.00    3.00
1463     0.00    0.00
1464     4.19    0.25

[1465 rows x 2 columns]

In [ ]:
#number of movies titles directed by CN

In [ ]:
data.loc[data["director_name"]=="Christopher Nolan"]["title"].count()

8

In [ ]:
data["director_name"].value_counts()

Steven Spielberg      26
Martin Scorsese       19
Clint Eastwood        19
Woody Allen           18
Ridley Scott          16
                      ..
Tim Hill               5
Jonathan Liebesman     5
Roman Polanski         5
Larry Charles          5
Nicole Holofcener      5
Name: director_name, Length: 199, dtype: int64

In [ ]:
data.groupby("director_name")

In [ ]:
data.groupby("director_name").ngroups

199

In [ ]:
data.groupby("director_name").groups

{'Adam McKay': [635, 636, 637, 638, 639, 640], 'Adam Shankman': [792, 793, 794, 795, 796, 797, 798, 799], 'Alejandro González Iñárritu': [465, 466, 467, 468, 469, 470], 'Alex Proyas': [425, 426, 427, 428, 429], 'Alexander Payne': [1341, 1342, 1343, 1344, 1345], 'Andrew Adamson': [63, 64, 65, 66, 67], 'Andrew Niccol': [1177, 1178, 1179, 1180, 1181], 'Andrzej Bartkowiak': [913, 914, 915, 916, 917], 'Andy Fickman': [1152, 1153, 1154, 1155, 1156, 1157], 'Andy Tennant': [883, 884, 885, 886, 887, 888], 'Ang Lee': [441, 442, 443, 444, 445, 446, 447, 448], 'Anne Fletcher': [1262, 1263, 1264, 1265, 1266], 'Antoine Fuqua': [856, 857, 858, 859, 860, 861, 862, 863], 'Atom Egoyan': [1405, 1406, 1407, 1408, 1409, 1410], 'Barry Levinson': [870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882], 'Barry Sonnenfeld': [73, 74, 75, 76, 77, 78, 79], 'Ben Stiller': [721, 722, 723, 724, 725], 'Bill Condon': [454, 455, 456, 457, 458], 'Bobby Farrelly': [918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928], 'Brad Anderson': [1439, 1440, 1441, 1442, 1443], 'Brett Ratner': [131, 132, 133, 134, 135, 136, 137, 138, 139], 'Brian De Palma': [740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751], 'Brian Helgeland': [1141, 1142, 1143, 1144, 1145], 'Brian Levant': [1017, 1018, 1019, 1020, 1021, 1022], 'Brian Robbins': [1011, 1012, 1013, 1014, 1015, 1016], 'Bryan Singer': [47, 48, 49, 50, 51, 52, 53, 54], 'Cameron Crowe': [902, 903, 904, 905, 906, 907], 'Catherine Hardwicke': [1256, 1257, 1258, 1259, 1260, 1261], 'Chris Columbus': [493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503], 'Chris Weitz': [105, 106, 107, 108, 109, 110], 'Christopher Nolan': [21, 22, 23, 24, 25, 26, 27, 28], 'Chuck Russell': [641, 642, 643, 644, 645, 646], 'Clint Eastwood': [934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952], 'Curtis Hanson': [1105, 1106, 1107, 1108, 1109, 1110, 1111], 'Danny Boyle': [1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176], 'Darren Aronofsky': [487, 488, 489, 490, 491, 492], 'Darren Lynn Bousman': [1455, 1456, 1457, 1458, 1459], 'David Ayer': [277, 278, 279, 280, 281, 282], 'David Cronenberg': [1199, 1200, 1201, 1202, 1203, 1204, 1205], 'David Fincher': [302, 303, 304, 305, 306, 307, 308, 309, 310, 311], 'David Gordon Green': [1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213], 'David Koepp': [1068, 1069, 1070, 1071, 1072], 'David Lynch': [1239, 1240, 1241, 1242, 1243], 'David O. Russell': [1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030], 'David R. Ellis': [1234, 1235, 1236, 1237, 1238], 'David Zucker': [1229, 1230, 1231, 1232, 1233], 'Dennis Dugan': [726, 727, 728, 729, 730, 731, 732, 733, 734], 'Donald Petrie': [1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051], 'Doug Liman': [290, 291, 292, 293, 294, 295, 296], 'Edward Zwick': [418, 419, 420, 421, 422, 423, 424], 'F. Gary Gray': [848, 849, 850, 851, 852, 853, 854, 855], 'Francis Ford Coppola': [1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104], 'Francis Lawrence': [312, 313, 314, 315, 316], 'Frank Coraci': [600, 601, 602, 603, 604, 605, 606], 'Frank Oz': [680, 681, 682, 683, 684, 685, 686], 'Garry Marshall': [894, 895, 896, 897, 898, 899, 900, 901], 'Gary Fleder': [1158, 1159, 1160, 1161, 1162, 1163], 'Gary Winick': [787, 788, 789, 790, 791], 'Gavin O'Connor': [1369, 1370, 1371, 1372, 1373], 'George A. Romero': [774, 775, 776, 777, 778, 779], 'George Clooney': [908, 909, 910, 911, 912], 'George Miller': [361, 362, 363, 364, 365, 366, 367], 'Gore Verbinski': [7, 8, 9, 10, 11, 12, 13], 'Guillermo del Toro': [180, 181, 182, 183, 184], 'Gus Van Sant': [1244, 1245, 1246, 1247, 1248, 1249, 1250], 'Guy Ritchie': [510, 511, 512, 513, 514, 515, 516], 'Harold Ramis': [1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043], 'Ivan Reitman': [805, 806, 807, 808, 809, 810, 811, 812], 'James Cameron': [0, 1, 2, 3, 4, 5, 6], 'James Ivory': [1432, 1433, 1434, 1435, 1436, 1437, 1438], 'James Mangold': [559, 560, 561, 562, 563, 564, 565, 566], 'James Wan': [166, 167, 168, 169, 170, 171, 172], 'Jan de Bont': [595, 596, 597, 598, 599], 'Jason Friedberg': [1364, 1365, 1366, 1367, 1368], 'Jason Reitman': [1336, 1337, 1338, 1339, 1340], 'Jaume Collet-Serra': [1146, 1147, 1148, 1149, 1150, 1151], 'Jay Roach': [687, 688, 689, 690, 691, 692, 693, 694], 'Jean-Pierre Jeunet': [1031, 1032, 1033, 1034, 1035], 'Joe Dante': [830, 831, 832, 833, 834, 835], 'Joe Wright': [402, 403, 404, 405, 406, 407], 'Joel Coen': [1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062], 'Joel Schumacher': [532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544], 'John Carpenter': [1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191], 'John Glen': [1251, 1252, 1253, 1254, 1255], 'John Landis': [1164, 1165, 1166, 1167, 1168], 'John Madden': [1086, 1087, 1088, 1089, 1090], 'John McTiernan': [522, 523, 524, 525, 526, 527, 528, 529, 530, 531], 'John Singleton': [836, 837, 838, 839, 840, 841, 842], 'John Whitesell': [1112, 1113, 1114, 1115, 1116], 'John Woo': [545, 546, 547, 548, 549, 550, 551], 'Jon Favreau': [243, 244, 245, 246, 247, 248], 'Jon M. Chu': [449, 450, 451, 452, 453], 'Jon Turteltaub': [317, 318, 319, 320, 321, 322, 323], 'Jonathan Demme': [819, 820, 821, 822, 823], 'Jonathan Liebesman': [388, 389, 390, 391, 392], 'Judd Apatow': [889, 890, 891, 892, 893], 'Justin Lin': [211, 212, 213, 214, 215], 'Kenneth Branagh': [381, 382, 383, 384, 385, 386, 387], 'Kenny Ortega': [1006, 1007, 1008, 1009, 1010], 'Kevin Reynolds': [297, 298, 299, 300, 301], ...}

In [ ]:
data.loc[data["director_name"]=="Christopher Nolan"]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
21,43600,250.0,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,1.0,834.94,834.94
22,43662,185.0,187,1004.56,The Dark Knight,8.2,12002,2008,Jul,Wednesday,Christopher Nolan,1.0,819.56,819.56
23,43692,165.0,724,675.12,Interstellar,8.1,10867,2014,Nov,Wednesday,Christopher Nolan,1.0,510.12,510.12
24,43693,160.0,167,825.53,Inception,8.1,13752,2010,Jul,Wednesday,Christopher Nolan,1.0,665.53,665.53
25,43716,150.0,115,374.22,Batman Begins,7.5,7359,2005,Jun,Friday,Christopher Nolan,1.0,224.22,224.22
26,44630,46.0,41,113.71,Insomnia,6.8,1148,2002,May,Friday,Christopher Nolan,1.0,67.71,67.71
27,44793,40.0,74,109.68,The Prestige,8.0,4391,2006,Oct,Thursday,Christopher Nolan,1.0,69.68,69.68
28,47170,9.0,60,39.72,Memento,8.1,4028,2000,Oct,Wednesday,Christopher Nolan,1.0,30.72,30.72

In [ ]:
data.groupby("director_name").get_group("Christopher Nolan")

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
21,43600,250.0,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,1.0,834.94,834.94
22,43662,185.0,187,1004.56,The Dark Knight,8.2,12002,2008,Jul,Wednesday,Christopher Nolan,1.0,819.56,819.56
23,43692,165.0,724,675.12,Interstellar,8.1,10867,2014,Nov,Wednesday,Christopher Nolan,1.0,510.12,510.12
24,43693,160.0,167,825.53,Inception,8.1,13752,2010,Jul,Wednesday,Christopher Nolan,1.0,665.53,665.53
25,43716,150.0,115,374.22,Batman Begins,7.5,7359,2005,Jun,Friday,Christopher Nolan,1.0,224.22,224.22
26,44630,46.0,41,113.71,Insomnia,6.8,1148,2002,May,Friday,Christopher Nolan,1.0,67.71,67.71
27,44793,40.0,74,109.68,The Prestige,8.0,4391,2006,Oct,Thursday,Christopher Nolan,1.0,69.68,69.68
28,47170,9.0,60,39.72,Memento,8.1,4028,2000,Oct,Wednesday,Christopher Nolan,1.0,30.72,30.72

In [ ]:
#Give me the min and max years for each director's movies

In [ ]:
data.groupby("director_name")["year"].agg(["min","max"])

                              min   max
director_name
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

In [ ]:
data.groupby("director_name")["year"].agg([np.min,np.max])

                             amin  amax
director_name
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

In [ ]:
#high budget movies : budget of atleast 100 M $
#high budget director
#return all the movies of a high budget director

data.groupby("director_name")["budget"].max()

director_name
Adam McKay                     100.0
Adam Shankman                   80.0
Alejandro González Iñárritu    135.0
Alex Proyas                    140.0
Alexander Payne                 30.0
                               ...
Wes Craven                      40.0
Wolfgang Petersen              175.0
Woody Allen                     30.0
Zack Snyder                    250.0
Zhang Yimou                     94.0
Name: budget, Length: 199, dtype: float64

In [ ]:
dir_high_budget = data.groupby("director_name")["budget"].max().reset_index()
dir_high_budget

                   director_name  budget
0                     Adam McKay   100.0
1                  Adam Shankman    80.0
2    Alejandro González Iñárritu   135.0
3                    Alex Proyas   140.0
4                Alexander Payne    30.0
..                           ...     ...
194                   Wes Craven    40.0
195            Wolfgang Petersen   175.0
196                  Woody Allen    30.0
197                  Zack Snyder   250.0
198                  Zhang Yimou    94.0

[199 rows x 2 columns]

In [ ]:
dir_high_budget.loc[dir_high_budget["budget"]>=100]

                   director_name  budget
0                     Adam McKay   100.0
2    Alejandro González Iñárritu   135.0
3                    Alex Proyas   140.0
5                 Andrew Adamson   225.0
10                       Ang Lee   137.0
..                           ...     ...
187                  Tom Shadyac   175.0
188                   Tom Tykwer   102.0
189                   Tony Scott   100.0
195            Wolfgang Petersen   175.0
197                  Zack Snyder   250.0

[85 rows x 2 columns]

In [ ]:
names = dir_high_budget.loc[dir_high_budget["budget"]>=100,"director_name"]
names

0                       Adam McKay
2      Alejandro González Iñárritu
3                      Alex Proyas
5                   Andrew Adamson
10                         Ang Lee
                  ...
187                    Tom Shadyac
188                     Tom Tykwer
189                     Tony Scott
195              Wolfgang Petersen
197                    Zack Snyder
Name: director_name, Length: 85, dtype: object

In [ ]:
data.loc[data["director_name"].isin(names)]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
0,43597,237.0,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97
1,43622,200.0,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03
2,43876,100.0,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00
3,43879,115.0,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88
4,44184,70.0,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,44255,45.0,42,73.76,Death Race,6.0,1175,2008,Aug,Friday,Paul W.S. Anderson,1.0,28.76,28.76
758,44367,60.0,29,26.67,Event Horizon,6.5,742,1997,Aug,Friday,Paul W.S. Anderson,1.0,-33.33,-33.33
759,44396,60.0,2,300.23,Resident Evil: Afterlife,5.8,1363,2010,Sep,Thursday,Paul W.S. Anderson,1.0,240.23,240.23
760,44992,33.0,40,102.98,Resident Evil,6.4,2065,2002,Mar,Friday,Paul W.S. Anderson,1.0,69.98,69.98
761,45697,18.0,16,122.20,Mortal Kombat,5.4,442,1995,Aug,Friday,Paul W.S. Anderson,1.0,104.20,104.20

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0,25.29,25.29
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0,6.87,6.87
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0,-3.00,-3.00
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0,0.00,0.00
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0,3.94,3.94

In [ ]:
data.groupby("director_name").filter(lambda x:x["budget"].max()>=100)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
0,43597,237.0,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97
1,43622,200.0,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03
2,43876,100.0,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00
3,43879,115.0,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88
4,44184,70.0,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,44255,45.0,42,73.76,Death Race,6.0,1175,2008,Aug,Friday,Paul W.S. Anderson,1.0,28.76,28.76
758,44367,60.0,29,26.67,Event Horizon,6.5,742,1997,Aug,Friday,Paul W.S. Anderson,1.0,-33.33,-33.33
759,44396,60.0,2,300.23,Resident Evil: Afterlife,5.8,1363,2010,Sep,Thursday,Paul W.S. Anderson,1.0,240.23,240.23
760,44992,33.0,40,102.98,Resident Evil,6.4,2065,2002,Mar,Friday,Paul W.S. Anderson,1.0,69.98,69.98
761,45697,18.0,16,122.20,Mortal Kombat,5.4,442,1995,Aug,Friday,Paul W.S. Anderson,1.0,104.20,104.20

In [ ]:
data.groupby("director_name").filter(lambda x:x["budget"].min()<=100)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0,25.29,25.29
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0,6.87,6.87
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0,-3.00,-3.00
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0,0.00,0.00
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0,3.94,3.94

In [ ]:
#Risky or not

In [ ]:
def func(x):
    x["risky"]=x["budget"]-x["revenue"].mean()>=0
    return x

In [ ]:
#import warnings
#warnings.filterwarnings("ignore", category=DeprecationWarning)

data_risky=data.groupby("director_name").apply(func)

<ipython-input-113-e2ae98467a77>:4: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  data_risky=data.groupby("director_name").apply(func)

In [ ]:
data_risky

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2,risky
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97,False
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03,False
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00,False
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88,False
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0,25.29,25.29,False
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0,6.87,6.87,False
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0,-3.00,-3.00,False
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0,0.00,0.00,False
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0,3.94,3.94,False

In [ ]:
data_risky.loc[data_risky["risky"]]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2,risky
55,43608,200.0,107,586.09,Quantum of Solace,6.1,2965,2008,Oct,Thursday,Marc Forster,1.0,386.09,386.09,True
56,43642,200.0,81,531.86,World War Z,6.7,5560,2013,Jun,Thursday,Marc Forster,1.0,331.86,331.86,True
68,43614,380.0,135,1045.71,Pirates of the Caribbean: On Stranger Tides,6.4,4948,2011,May,Saturday,Rob Marshall,1.0,665.71,665.71,True
89,43618,200.0,37,310.67,Robin Hood,6.2,1398,2010,May,Wednesday,Ridley Scott,1.0,110.67,110.67,True
111,43624,209.0,64,303.03,Battleship,5.5,2114,2012,Apr,Wednesday,Peter Berg,1.0,94.03,94.03,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,47229,5.0,3,4.84,90 Minutes in Heaven,5.4,40,2015,Sep,Friday,Michael Polish,1.0,-0.16,-0.16,True
1450,46727,10.0,2,0.00,Adam Resurrected,6.4,22,2008,Aug,Friday,Paul Schrader,NaN,-10.00,-10.00,True
1451,46975,7.0,7,2.06,Auto Focus,6.1,56,2002,Oct,Friday,Paul Schrader,NaN,-4.94,-4.94,True
1452,47233,5.0,6,0.00,Light Sleeper,5.7,15,1992,Aug,Friday,Paul Schrader,NaN,-5.00,-5.00,True
1453,47263,15.0,10,0.00,Dying of the Light,4.5,118,2014,Dec,Thursday,Paul Schrader,NaN,-15.00,-15.00,True

In [ ]:
data.groupby(["director_name","title"])

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit_method_1,method2
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1.0,2550.97,2550.97
1,43622,200.00,100,1845.03,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,1.0,1645.03,1645.03
2,43876,100.00,101,520.00,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,1.0,420.00,420.00
3,43879,115.00,38,378.88,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,1.0,263.88,263.88
4,44184,70.00,24,90.00,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,1.0,20.00,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0.00,14,25.29,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,0.0,25.29,25.29
1461,47023,6.50,11,13.37,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,0.0,6.87,6.87
1462,47524,3.00,5,0.00,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,0.0,-3.00,-3.00
1463,47962,0.00,0,0.00,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,0.0,0.00,0.00
1464,48229,0.25,1,4.19,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,0.0,3.94,3.94